import dotenv from 'dotenv';

dotenv.config();
const env = process.env;

export default {
	NAME: env.NAME,
	VERSION: env.VERSION,
	ENV: env.NODE_ENV,
	HOST: env.HOST,
	PORT: env.PORT,
	LOG_LEVEL: env.LOG_LEVEL,

	DB_USER: env.DB_USER,
	DB_PASS: env.DB_PASS,
	DB_NAME: env.DB_NAME,
	DB_HOST: env.DB_HOST,
	DB_PORT: env.DB_PORT,

	JWT_SECRET: env.JWT_SECRET,
	JWT_REFRESH_SECRET: env.JWT_REFRESH_SECRET,
	ROOT_USERNAME: env.ROOT_USERNAME,
	ROOT_PASSWORD: env.ROOT_PASSWORD,

	SMSIR_ACCESS_KEY: env.SMSIR_ACCESS_KEY,
	SMSIR_LINE_NUMBER: env.SMSIR_LINE_NUMBER,

	UPLOAD_TEMP_DIRECTORY: env.UPLOAD_TEMP_DIRECTORY,

	OPENSEARCH_URL: env.OPENSEARCH_URL,
	OPENSEARCH_USER: env.OPENSEARCH_USER,
	OPENSEARCH_PASS: env.OPENSEARCH_PASS,

	GENERAL_QUEUE_INTERVAL: env.GENERAL_QUEUE_INTERVAL,
};
