import dotenv from 'dotenv';

dotenv.config();
const env = process.env;

export default {
	NAME: env.NAME,
	VERSION: env.VERSION,
	ENV: env.NODE_ENV,
	HOST: env.HOST,
	PORT: env.PORT,
	LOG_LEVEL: env.LOG_LEVEL,

	DB_USER: env.DB_USER,
	DB_PASS: env.DB_PASS,
	DB_NAME: env.DB_NAME,
	DB_HOST: env.DB_HOST,
	DB_PORT: env.DB_PORT,

	SMSIR_ACCESS_KEY: env.SMSIR_ACCESS_KEY,
	SMSIR_LINE_NUMBER: env.SMSIR_LINE_NUMBER,

	// TODO V0
	JWT_SECRET: env.JWT_SECRET,
	JWT_REFRESH_SECRET: env.JWT_REFRESH_SECRET,
	// V1
	AUTH_SECRET: env.AUTH_SECRET!,

	FRONT_URL: env.FRONT_URL,
	CORS_URLS: env.CORS_URLS,

	// Payment gateways
	PG_MELLAT_TERMINAL_ID: env.PG_MELLAT_TERMINAL_ID,
	PG_MELLAT_USERNAME: env.PG_MELLAT_USERNAME,
	PG_MELLAT_PASSWORD: env.PG_MELLAT_PASSWORD,
	PG_ZARINPAL_TOKEN: env.PG_ZARINPAL_TOKEN,
	PG_SAMAN_TOKEN: env.PG_SAMAN_TOKEN,

	COUPON_CODE: env.COUPON_CODE ?? null,

	UPLOAD_TEMP_DIRECTORY: env.UPLOAD_TEMP_DIRECTORY,

	OPENSEARCH_URL: env.OPENSEARCH_URL,
	OPENSEARCH_USER: env.OPENSEARCH_USER,
	OPENSEARCH_PASS: env.OPENSEARCH_PASS,
};
